id: A7844CD4B
base_file: fE7CB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:56:16.881078
  last_modified_at: 2022-05-30 21:56:16.881081
