id: A7844CD4B
base_file: f0E61.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:56:16.866639
  last_modified_at: 2022-05-30 21:56:16.866647
